/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/ngclogo.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.logo.geometry} material={materials.Cor} position={[0.08, 0.17, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[100, 1, 100]} />
    </group>
  )
}

useGLTF.preload('/ngclogo.gltf')
